
services:
  app:
    build: ./app
    image: yumpy-dog 
    depends_on: [db]  
    container_name: yump_app
    restart: unless-stopped

    #environment:
      #POSTGRES_USER: yumpy
      #POSTGRES_DB: yump_db

    env_file:
      - ./app/.env  
    ports:
      - "5000:5000"
  
  db:
    build: ./database
    #image: postgres:17.6  # Use official image
    container_name: yumpy_postgres
    restart: unless-stopped

    env_file:
      - ./database/.env  
    #environment:
      #POSTGRES_USER: yumpy
      #POSTGRES_PASSWORD: ${DB_PASSWORD}  # Use env var
      #POSTGRES_DB: yump_db
    volumes:
      - postgres_data:/home/wheels/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d:ro

      
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yumpy -d yump_db"]
      interval: 10s
      timeout: 3s
      retries: 3


volumes:
  postgres_data:
    driver: local
